---
- name: Converge
  hosts: all
  tasks:
    - name: "Include palekiwi.nfs_server"
      ansible.builtin.include_role:
        name: "palekiwi.nfs_server"

    - name: Place an example directory within the default mount.
      become: true
      ansible.builtin.file:
        path: /srv/nfs/testfile
        mode: "0755"
        state: directory
